[package]
name = "cf-rust-deploy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
axum = { version = "0.8", default-features = false }
tower-service = "0.3"
worker = { version = "0.7", features = ["http", "axum"] }
worker-macros = { version = "0.7" }
