[package]
name = "cf-rust-deploy"
version = "0.1.0"
edition = "2021"
authors = ["yamazaki-yuki-23 <natural4083@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = { version = "0.7" }
worker-macros = { version = "0.7" }
